# Generated by Django 2.2 on 2020-09-25 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lec_app', '0002_wizard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geocache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=30)),
                ('treasure', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dragon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_geocaches', to='lec_app.Dragon')),
            ],
        ),
    ]
