# Generated by Django 2.2 on 2020-09-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_app', '0003_geocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='dragons_that_found',
            field=models.ManyToManyField(related_name='found_geocaches', to='lec_app.Dragon'),
        ),
    ]
